on:
  push:
    branches:
    - main
jobs:
  build_client:
    name: build client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build Vite app
      run: npm run build
